package com.mn.tiger.download.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.mn.tiger.download.db.Downloader;

import com.mn.tiger.download.db.DownloaderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloaderDaoConfig;

    private final DownloaderDao downloaderDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloaderDaoConfig = daoConfigMap.get(DownloaderDao.class).clone();
        downloaderDaoConfig.initIdentityScope(type);

        downloaderDao = new DownloaderDao(downloaderDaoConfig, this);

        registerDao(Downloader.class, downloaderDao);
    }
    
    public void clear() {
        downloaderDaoConfig.getIdentityScope().clear();
    }

    public DownloaderDao getDownloaderDao() {
        return downloaderDao;
    }

}
