package com.mn.tiger.download.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DOWNLOADER".
 */
public class Downloader implements java.io.Serializable {

    private long id;
    /** Not-null value. */
    private String url;
    private String params;
    private long fileSize;
    private long completeSize;
    private int downloadStatus;
    /** Not-null value. */
    private String savePath;
    private int requestType;
    private String checkKey;
    private boolean accessRanges;
    private int errorCode;
    private String errorMsg;
    /** Not-null value. */
    private String taskClsName;
    /** Not-null value. */
    private String paramsClsName;
    private String downloadType;
    /** Not-null value. */
    private java.util.Date createTime;
    private boolean softDelete;
    private String extras;

    public Downloader() {
    }

    public Downloader(long id) {
        this.id = id;
    }

    public Downloader(long id, String url, String params, long fileSize, long completeSize, int downloadStatus, String savePath, int requestType, String checkKey, boolean accessRanges, int errorCode, String errorMsg, String taskClsName, String paramsClsName, String downloadType, java.util.Date createTime, boolean softDelete, String extras) {
        this.id = id;
        this.url = url;
        this.params = params;
        this.fileSize = fileSize;
        this.completeSize = completeSize;
        this.downloadStatus = downloadStatus;
        this.savePath = savePath;
        this.requestType = requestType;
        this.checkKey = checkKey;
        this.accessRanges = accessRanges;
        this.errorCode = errorCode;
        this.errorMsg = errorMsg;
        this.taskClsName = taskClsName;
        this.paramsClsName = paramsClsName;
        this.downloadType = downloadType;
        this.createTime = createTime;
        this.softDelete = softDelete;
        this.extras = extras;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public String getParams() {
        return params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public long getFileSize() {
        return fileSize;
    }

    public void setFileSize(long fileSize) {
        this.fileSize = fileSize;
    }

    public long getCompleteSize() {
        return completeSize;
    }

    public void setCompleteSize(long completeSize) {
        this.completeSize = completeSize;
    }

    public int getDownloadStatus() {
        return downloadStatus;
    }

    public void setDownloadStatus(int downloadStatus) {
        this.downloadStatus = downloadStatus;
    }

    /** Not-null value. */
    public String getSavePath() {
        return savePath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSavePath(String savePath) {
        this.savePath = savePath;
    }

    public int getRequestType() {
        return requestType;
    }

    public void setRequestType(int requestType) {
        this.requestType = requestType;
    }

    public String getCheckKey() {
        return checkKey;
    }

    public void setCheckKey(String checkKey) {
        this.checkKey = checkKey;
    }

    public boolean getAccessRanges() {
        return accessRanges;
    }

    public void setAccessRanges(boolean accessRanges) {
        this.accessRanges = accessRanges;
    }

    public int getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(int errorCode) {
        this.errorCode = errorCode;
    }

    public String getErrorMsg() {
        return errorMsg;
    }

    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }

    /** Not-null value. */
    public String getTaskClsName() {
        return taskClsName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTaskClsName(String taskClsName) {
        this.taskClsName = taskClsName;
    }

    /** Not-null value. */
    public String getParamsClsName() {
        return paramsClsName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setParamsClsName(String paramsClsName) {
        this.paramsClsName = paramsClsName;
    }

    public String getDownloadType() {
        return downloadType;
    }

    public void setDownloadType(String downloadType) {
        this.downloadType = downloadType;
    }

    /** Not-null value. */
    public java.util.Date getCreateTime() {
        return createTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public boolean getSoftDelete() {
        return softDelete;
    }

    public void setSoftDelete(boolean softDelete) {
        this.softDelete = softDelete;
    }

    public String getExtras() {
        return extras;
    }

    public void setExtras(String extras) {
        this.extras = extras;
    }

}
